# Generated by Django 3.0.5 on 2021-02-24 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtok',
            name='cloudToken',
            field=models.CharField(default=django.utils.timezone.now, max_length=2500),
            preserve_default=False,
        ),
    ]
